DROP DATABASE IF EXISTS weathersharing;
CREATE DATABASE weathersharing;

use weathersharing;
DROP TABLE IF EXISTS `user`;
CREATE TABLE user(
	id INT UNSIGNED AUTO_INCREMENT COMMENT '用户自增长id',
	username VARCHAR(50) DEFAULT NULL COMMENT '用户名',
	passwd VARCHAR(255) DEFAULT NULL COMMENT '密码',
	care_city VARCHAR(255) DEFAULT NULL COMMENT '关注城市',
	portrait VARCHAR(255) DEFAULT NULL COMMENT '用户头像',
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `img`;
CREATE TABLE img(
	id INT UNSIGNED AUTO_INCREMENT COMMENT '图片自增长id',
	img VARCHAR(255) DEFAULT NULL COMMENT '图片url',
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `upload`;
CREATE TABLE upload(
	id INT UNSIGNED AUTO_INCREMENT COMMENT '上传关系表id',
	upload_time DATETIME DEFAULT NULL COMMENT '上传时间',
	upload_img_id INT UNSIGNED DEFAULT NULL COMMENT '上传照片id',
	upload_user_id INT UNSIGNED DEFAULT NULL COMMENT '上传用户id',
	upload_city_id INT UNSIGNED DEFAULT NULL COMMENT '上传城市id',
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `city`;
CREATE TABLE city(
	id INT UNSIGNED AUTO_INCREMENT COMMENT '城市id',
	city_name VARCHAR(255) DEFAULT NULL COMMENT '城市名称',
	city_ip VARCHAR(255)DEFAULT NULL COMMENT '城市所在地的ip地址',
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


